modLoader = "javafml"
loaderVersion = "[34,)"
issueTrackerURL = "https://github.com/cofh/feedback"
license = "CoFH - Don't Be A Jerk (Learn, Don't Steal)"

[[mods]]
modId = "tools_complement"
version = "${file.jarVersion}"
displayName = "Tool's Complement"
updateJSONURL = "https://raw.github.com/cofh/version/master/tools_complement/update.json"
displayURL = "https://teamcofh.com/"
logoFile = "logo.png"
itemIcon = "tools_complement:diamond_sickle"
credits = "Team CoFH"
authors = "King Lemming"
description = '''
Adds Armor and Tool sets in various vanilla and modded materials!

Any given set can be disabled in the config and will only appear if the appropriate material is available.

Suitable for both lightly and heavily modded worlds.
'''
[[dependencies.tools_complement]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.tools_complement]]
modId = "forge"
mandatory = true
versionRange = "[40.1.76,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.tools_complement]]
modId = "cofh_core"
mandatory = true
versionRange = "[9.2,9.3]"
ordering = "AFTER"
side = "BOTH"